name: glorifi
description: The GloriFi mobile experience

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+112

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  camera: 0.9.4+24
  carousel_slider: ^4.0.0
  chewie: ^1.2.2
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.5
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.4
  dio_http_formatter: ^2.1.0
  email_validator: ^2.0.1
  alice: ^0.2.5
  fl_chart: ^0.45.0
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^19.4.56
  pie_chart: ^5.1.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_swipable: ^1.2.1
  geolocator: ^8.2.0
  get: 4.6.1
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  local_auth: ^1.1.10
  localstorage: ^4.0.0+1
  logger: ^1.1.0
  pin_code_fields: 7.3.0
  percent_indicator: 4.0.0
  shared_preferences: ^2.0.12
  storybook_flutter: ^0.8.0
  timeago: ^3.1.0
  tuple: ^2.0.0
  webview_flutter: ^3.0.0
  webview_flutter_plus: ^0.3.0+1
  lottie: ^1.2.1
  video_player: ^2.2.7
  http: ^0.13.3
  universal_html: ^2.0.8
  google_fonts: ^2.3.1
  jwt_decoder: ^2.0.1
  plaid_flutter: ^2.2.1
  provider:
  url_launcher: ^6.0.18
  cached_network_image: ^3.2.0
  flutter_share: ^2.0.0
  url_strategy: ^0.2.0
  photo_view: ^0.13.0
  printing: ^5.7.2
  brokerage:
    git:
      #url: https://animo-gitlab.southcentralus.cloudapp.azure.com/brokerage/flutter-glorifi-brokerage
      url: https://gitlab+deploy-token-3:DRD6rELU1vygAJriKug_@animo-gitlab.southcentralus.cloudapp.azure.com/animo-admins/flutter-glorifi-brokerage
      ref: v1.0
      path: brokerage
  youtube_plyr_iframe: ^2.0.7
  package_info_plus: ^1.4.0
  flutter_switch: ^0.3.2
  dots_indicator: ^2.1.0
  otp_text_field: ^1.1.2
  flutter_typeahead: ^3.1.3
  shimmer: ^2.0.0
  #for image manipulation
  image: ^3.1.3
  advance_pdf_viewer_fork: ^2.0.0
  webview_cookie_manager: ^2.0.6
  enum_to_string: ^2.0.1
  app_settings: ^4.1.5
  safe_device: 1.1.1
  contentful: ^3.0.5
  contentful_rich_text: ^1.0.1
  dotted_border: ^2.0.0+2
  flutter_widget_from_html_core: ^0.8.5+1
  firebase_crashlytics: ^2.6.3
  firebase_core: ^1.16.0
  firebase_dynamic_links: ^4.2.5
  custom_refresh_indicator: 1.1.1
  country_picker: ^2.0.15
  flutter_multi_formatter: ^2.5.1
  permission_handler: ^8.2.6
  us_states: ^1.2.0
  instant: ^0.4.1
  dart_ipify: ^1.1.1
  flutter_html: ^3.0.0-alpha.3
  flutter_calendar_carousel: 2.1.0
  # syncfusion_flutter_gauges: ^19.4.56

dev_dependencies:
  change_app_package_name: ^1.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  dart_code_metrics: ^4.15.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  test_cov: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/files/
    - assets/company_logo/
    - assets/images/
    - assets/images/glorifi_logo/
    - assets/images/splash/
    - assets/icons/
    - assets/video/Together.mp4
    - assets/video/startup.mp4
    - assets/json/
    - assets/personetics/
    - assets/icons/personal_snapshot/
    # Apply for credit card - Choose your credit card design
    - assets/images/credit_card_design/
    - assets/images/products/
    - assets/images/products/tmp_promo/
    # These are all needed individually for Personetics to work properly
    - assets/personetics/
    - assets/personetics/personetics-glorifi/js/
    - assets/personetics/personetics-glorifi/css/
    - assets/personetics/personetics-glorifi/
    - assets/personetics/glorifi_home/
    - assets/personetics/personetics-glorifi/resources/assets/
    - assets/personetics/personetics-glorifi/resources/fonts/
    - assets/personetics/personetics-glorifi/resources/assets/ui_elements/loader/
    - assets/personetics/personetics-glorifi/resources/assets/ui_elements/rating_icons/
    - assets/personetics/personetics-glorifi/resources/assets/navigation/chevron/

  fonts:
    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo-Regular.ttf
        - asset: assets/fonts/Arvo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arvo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arvo-BoldItalic.ttf
          style: italic
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
    - family: Univers
      fonts:
        - asset: assets/fonts/UniversCnRg.ttf
          weight: 400
        - asset: assets/fonts/UniversCnBold.ttf
          weight: 700
    - family: UniversWide
      fonts:
        - asset: assets/fonts/UniversLight.ttf
          weight: 300
        - asset: assets/fonts/UniversRegular.ttf
          weight: 400
        - asset: assets/fonts/UniversBold.ttf
          weight: 700
