enum RewardPointRuleType {
  COMPLETE_PROFILE,
  ENABLE_CREDIT_SCORE,
  LINK_BANK_ACCOUNT,
  LOCATION_PERMISSION,
  CAMERA_ACCESS,
  DOWNLOAD_GLORIFI_APP,
  SHARE_GLORIFI_APP,
  DEPOSIT_MONEY_INFO_SAVING,
  SET_UP_DIRECT_DEPOSIT,
  EARN_POINTS_WHILE_YOU_SAVE
}
