// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDcQDx79iEp_qG0GaNAQ2Y2blOafylWw',
    appId: '1:844451946578:web:214304ae569e0f3b2a3f8b',
    messagingSenderId: '844451946578',
    projectId: 'glorifi-f9440',
    authDomain: 'glorifi-f9440.firebaseapp.com',
    storageBucket: 'glorifi-f9440.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSOR0Rt1V-sU_5cCFIIfqkv04cO2VBqEo',
    appId: '1:844451946578:android:e4590f627259f1872a3f8b',
    messagingSenderId: '844451946578',
    projectId: 'glorifi-f9440',
    storageBucket: 'glorifi-f9440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9FGB211Fkpj40PQYDtnWQToS2M641aE0',
    appId: '1:844451946578:ios:ff1e96cf28202f5a2a3f8b',
    messagingSenderId: '844451946578',
    projectId: 'glorifi-f9440',
    storageBucket: 'glorifi-f9440.appspot.com',
    iosClientId: '844451946578-tu2f2b2ol5onqk02i02i0ocsrdmi50vv.apps.googleusercontent.com',
    iosBundleId: 'com.glorifi.temp',
  );
}
