enum SettingsName {
  APP_VERSION,
  GLORIFI,
  TERMS,
  PRIVACY,
  FINANCIAL_TERMS,
  CARDHOLDER_SERVICE,
  BUSINESS_SERVICES,
  FREE_SCHEDULE,
  CONSENT_TO_EMAILS_SMS,
  ONLINE_BANKING_AGREEMENT,
  ACCOUNT_INFORMATION_DISCLOSURES,
  REQUEST_MY_DATA,
  REQUEST_DATA_DELETION
}
